### ISSUE TITLE
Attribute Error Logs

### ISSUE THREAD

**Issue by jordy101091** [cyberjunky/home-assistant-hvcgroep#16]
I have this error in the logs, it prevents the component from loading correctly.

`Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:368
Integration: Sensor (documentation, issues)
First occurred: 11:23:38 (1 occurrences)
Last logged: 11:23:38

Error while setting up hvcgroep platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1278, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1002, in __async_calculate_state
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hvcgroep/sensor.py", line 282, in extra_state_attributes
    "datediff": self._datediff
                ^^^^^^^^^^^^^^
AttributeError: 'TrashSensor' object has no attribute '_datediff'
`

**Comment by cyberjunky** [comment]
@jordy101091 thank you for reporting, I fixed it in version 1.0.12!

**Comment by cyberjunky** [comment]
Closing because solved.
